---

- name: Deploy the VMs
  hosts: localhost
  vars:
       random_name:
         - aspire1
         - aspire2
         - aspire3
         - aspire4
         - aspire5
         - aspire6
         - aspire7
         - aspire8
         - aspire9
         - aspire10
         - aspire11
         - aspire12
         - aspire13
         - aspire14
         - aspire15
         - aspire16
         - aspire17
         - aspire18
         - aspire19
         - aspire20
         - aspire21
         - aspire22
  connection: local
  gather_facts: no
  tasks:
  - name: set vmname
    set_fact:
      vmname: "{{ random_name | random }}"
      
  - name: Create a VM
    vmware_guest:
      name: "{{ vmname }}"
      hostname: "192.168.5.226"
      validate_certs: False
      username: "administrator@vsphere.delta"
      password: "Passw0rd!"
      datacenter: "Delta"
      datastore: "datastore2"
      folder: "/Demo"
      state: poweredon
      template: demo-aspire
         
      networks:
      - name: "1050"
      - name: "1060"
      
  - name: Time before shutdown and destruction
    tags: sleep60
    wait_for:
      delay: 60
      timeout: 0
      
      
  - name: Gather facts from standalone ESXi server having datacenter as 'ha-datacenter'
    vmware_guest_facts:
      hostname: "192.168.5.226"
      validate_certs: False
      username: "administrator@vsphere.delta"
      password: "Passw0rd!"
      datacenter: "Delta"
      datastore: "datastore2"
      folder: "/Demo"
    delegate_to: localhost
    register: facts

## Debug to validate that the Playbook has the IP of the VM
    - debug: msg="IP is {{ hw_eth0.ipaddresses[0] }}"

## Add the IP to the hosts inventory to customize it
    - add_host: name={{ hw_eth0.ipaddresses[0] }} groups=virtual

-
  host:virtual

## Debug to validate that we have the name of the VM to change the hostname (Review Fact Caching)
  tasks:
    - debug: msg="{{ hostvars['localhost']['hw_name'] }}"


