---

- name: Deploy the VMs
  hosts: localhost
  vars:
       random_name:
         - aspire1
         - aspire2
         - aspire3
         - aspire4
         - aspire5
         - aspire6
         - aspire7
         - aspire8
         - aspire9
         - aspire10
         - aspire11
         - aspire12
         - aspire13
         - aspire14
         - aspire15
         - aspire16
         - aspire17
         - aspire18
         - aspire19
         - aspire20
         - aspire21
         - aspire22
  connection: local
  gather_facts: no
  tasks:
  - name: Instant Clone a VM
    community.vmware.vmware_guest_instant_clone_module:
      name: instantvm1
      hostname: "192.168.5.226"
      username: "administrator@vsphere.delta"
      password: "Passw0rd!"
      validate_certs: False
      folder: "/Demo"
      datastore: "datastore2"
      datacenter: "Delta"
      parent_vm: demo-aspire
      state: poweredon
      networks:
      - name: "1060"
      - name: "1050"
    register: vm_clone
    delegate_to: localhost
