---
- name: Add User and distribute key
  gather_facts: yes
  hosts: all

  tasks :

   - name: Ensure group "wheel" exists
     group:
       name: wheel
       state: present

   - name: Allow 'wheel' group to have passwordless sudo
     lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'
   
   - name: Add the user 'svc_ansible' with a bash shell, appending the group 'wheel' to the user's groups
     user:
      name: svc_ansible
      shell: /bin/bash
      groups: wheel
      append: yes
      
   - name: Set up authorized keys for the delta user
     authorized_key: 
      user: svc_ansible
    
