---
- name: Add User and distribute key
  gather_facts: yes
  hosts: all

  tasks :

   - name: Ensure group "wheel" exists
     group:
       name: wheel
       state: present

   - name: Allow 'wheel' group to have passwordless sudo
     lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'
   
   - name: Add the user 'svc_ansible' with a bash shell, appending the group 'wheel' to the user's groups
     user:
      name: svc_ansible
      shell: /bin/bash
      groups: wheel
      append: yes
      
   - name: Set up authorized keys for the delta user
     authorized_key: 
      user: svc_ansible
      key: "AAAAB3NzaC1yc2EAAAADAQABAAABAQC3pIGqWwnpXdQKMcxG3onfRQYW+P7jD1SKmrjicfvcnna3cJq2+4bNnjxNirUsOOxJ4BE1jkY+LwHnPZsix/gHN1fsTrq8eR73wgyI0r0F/zXBEEMUUFXlyt8Eomr2e2UDGGhDaSR3EBCIhuPooFudRu3yXMduyc16XrWPs4+Xrf1Y1sOdiQ3tFRq9huWDYO4SlITY7SJwtPzziNrb7az+cG/dQiB/8rB+JccwLHQKLEc7c8Zfer66ogcQO4oT1CAjPXVaw98lq+VR1VzXVxjXta2ZWFrKNy7ToyxeFgrtkPtR+JHPSpxkNm6fQC8Yr9dkfWutlrpgwwUuIysjJzNV"
    
