- name: Deploy on OpenStack
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Deploy an instance
    os_server:
      state: present
      name: vm1
      timeout: 200
      flavor: 693b91b1-16b7-4e5b-a222-a5de94c7a34d
      auto_ip: no
      network: 835b13ac-8db6-4060-9b6f-c56290ba7e7e
      security_groups: devzero_trust
      meta:
         os: ubuntu

