- name: Deploy on OpenStack
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Deploy an instance
    os_server:
      state: present
      name: vm1
      image: "auto-sync/ubuntu-bionic-18.04-amd64-server-20191021-disk1.img"
      timeout: 200
      flavor: ubuntu
      meta:
         os: ubuntu

