---
- name: Testing initial on openstack
  hosts: localhost
  
  tasks:
  - name: Create a new instance and attaches to a network and passes metadata to the instance
    os_server:
       state: present
       name: vm1
       image: "ubuntu"
       timeout: 200
       flavor: acc689de-3f3c-4814-9e59-4e6f7a191bdf
       auto_ip: no
       network: 27b3a2d7-5ca8-4aec-bc9c-09ccd7ce7879
       meta:
         os: ubuntu

  - name: Add second Server
    os_server:
       state: present
       name: vm2
       image: "centos"
       timeout: 200
       flavor: acc689de-3f3c-4814-9e59-4e6f7a191bdf
       auto_ip: no
       network: 27b3a2d7-5ca8-4aec-bc9c-09ccd7ce7879
       meta:
         os: centos
