- name: Deploy on OpenStack
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Deploy an instance
    os_server:
      state: present
      name: vm1
      image: "ubuntu"
      timeout: 200
      flavor: ubuntu
      auto_ip: no
      network: f422acbd-0fda-4891-bd85-382d33a7154f
      meta:
         os: ubuntu

