- name: Deploy on OpenStack
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Deploy an instance
    os_server:
      state: present
      name: vm1
      image: "ubuntu"
      timeout: 200
      flavor: ubuntu
      meta:
         os: ubuntu

