---

- name: Deploy the VMs
  hosts: localhost
  vars:
       random_name:
         - ubuntu1
         - ubuntu2
         - ubuntu3
         - ubuntu4
         - ubuntu5
         - ubuntu6
         - ubuntu7
         - ubuntu8
         - ubuntu9
         - ubuntu10
         - ubuntu11
         - ubuntu12
         - ubuntu13
         - ubuntu14
         - ubuntu15
         - ubuntu15
         - ubuntu16
         - ubuntu17
         - ubuntu18
         - ubuntu19
         - ubuntu20
         - ubuntu21
         - ubuntu22
  connection: local
  gather_facts: no
  tasks:
  - name: set vmname
    set_fact:
      vmname: "{{ random_name | random }}"
  - name: create vm
    vmware_guest:
         name: "{{ vmname }}"
         hostname: "192.168.5.226"
         validate_certs: False
         username: "administrator@vsphere.delta"
         password: "Passw0rd!"
         datacenter: "Delta"
         datastore: "datastore2"
         folder: "/Demo"
         state: poweredon
         template: demo-server
         wait_for_ip_address: yes
         
         networks:
         - name: "1050"
         - name: "1060"
         
  - name: Time before shutdown and destruction
    tags: sleep240
    wait_for:
      delay: 240
      timeout: 0

  - name: Destroy ubuntu
    vmware_guest:
        hostname: "192.168.5.226"
        validate_certs: False
        username: "administrator@vsphere.delta"
        password: "Passw0rd!"
        datacenter: "Delta"
        folder: "/Demo"
        name: "{{ vmname }}"
        state: absent
        force: yes
    delegate_to: localhost
    register: facts
